### ISSUE TITLE
PHP7.4 incompatibility

### ISSUE THREAD

**Issue by PlaidFoxSG** [craigpaul/moneris-api#12]
"array and string offset access syntax with curly braces is deprecated"

vendor\craigpaul\moneris-api\src\Response.php:183

`  if ($gateway->cvd && !is_null($code) && $code !== 'null' && !in_array($code{1}, $gateway->cvdCodes)) {`

**Comment by craigpaul** [comment]
Hey @PlaidFoxSG, wow, had no idea that was in there. I'd gladly accept a quick PR if you want to put it up. Otherwise, I'll try and fix that soon as I get a chance

**Comment by PlaidFoxSG** [comment]
quick response :) Yea, I'll do that.
