### ISSUE TITLE
Card verification does not require amount field

### ISSUE THREAD

**Issue by njaw** [craigpaul/moneris-api#5]
The card_verification endpoint does not need an 'amount' field present. Currently the valid function in the Transaction class makes this a requirement. Is it possible for you to update this? Here is the [Moneris API documentation](https://developer.moneris.com/Documentation/NA/E-Commerce%20Solutions/API/Card%20Verification?lang=php)

Thanks

**Comment by craigpaul** [comment]
Hey @njaw, sorry about the delay, just realized like an hour ago I was set to Not Watching on this repo. Anyway, I took a look, you are correct that it isn't required. See 714b162 and update your composer to `0.6.2`. Thanks for that catch!
