### ISSUE TITLE
Inconsistent Test Results Using Different `store_id` values

### ISSUE THREAD

**Issue by russdot** [craigpaul/moneris-api#8]
I have to use Moneris for payment processing and was _very_ excited to see such a wonderfully written PHP package (with tests!!) for consuming the truly awful Moneris API. Thank you!

After cloning the repo and running `composer install`, I decided to run the tests out of curiousity. While testing, I changed the `TestCase->id` field by cycling through the [available `store_id` values](https://developer.moneris.com/en/More/Testing/Testing%20a%20Solution) and had the following results:

Test Run # | `TestCase->id` | Test Results
--- | ------------ | -------------
1 | `store1` | Tests: 65, Assertions: 138, Failures: 38.
2 | `store2` | Tests: 65, Assertions: 169, Failures: 13.
3 | `store3` | Tests: 65, Assertions: 180, Failures: 1.
4 | `store4` | Tests: 65, Assertions: 168, Failures: 22.
5 | `store5` | Tests: 65, Assertions: 180, Failures: 1.

The failures in test runs 1, 2, 4 consist of multiple `GatewayTest`, `ProcessorTest`, `ResponseTest`, and `VaultTest` failures. I can provide these details if necessary.

However, only a single test fails in test runs 3, 5:

[`VaultTest::it_can_peek_into_the_vault_and_retrieve_a_full_credit_card_from_the_moneris_vault_with_a_valid_data_key`](https://github.com/craigpaul/moneris-api/blob/master/tests/VaultTest.php#L260)

This leads me to believe that the test stores `store1`, `store2`, and `store4` are not operating correctly or unavailable. My experience with Moneris is limited, so perhaps this is common?

The related test [`VaultTest::it_can_peek_into_the_vault_and_retrieve_a_masked_credit_card_from_the_moneris_vault_with_a_valid_data_key`](https://github.com/craigpaul/moneris-api/blob/master/tests/VaultTest.php#L241) is successful.

Using XDebug to investigate details (using `store3`):
```php
public function it_can_peek_into_the_vault_and_retrieve_a_full_credit_card_from_the_moneris_vault_with_a_valid_data_key()
{
    $response = $this->vault->add($this->card);
    $key = $response->receipt()->read('key');
// $key appears to be a valid data_key returned by Moneris

    $response = $this->vault->peek($key, true);
// $response->errors = []
// $response->failedAvs = false
// $response->failedCvd = false
// $response-> status = -23
// $response->successful = false

    $receipt = $response->receipt();
// $receipt->data->code = "987"
// $receipt->data->complete = false
// $receipt->data->message = "Invalid transaction"
// All other $receipt->data fields are "null" or null

    $this->assertTrue($response->successful); // FAILS
...
}
```

I am unable to locate any other details as to [*why* it is an invalid transaction](https://developer.moneris.com/en/More/Testing/Error%20Messages%20and%20Response%20Codes)... Or why `store1`, `store2` and `store4` have multiple, different test failures. Any help would be greatly appreciated. I hope I am just missing something. I'd be happy to provide more info or a PR if one is warranted. Cheers

**Comment by craigpaul** [comment]
Hey @russdot,

Just did a bit of testing locally and they are failing for me like that as well. These tests haven't been run in two years (if you take a look at Travis) since there hasn't been any changes. The unfortunate part about Moneris is that they have to run against a live test environment. 

In terms of why they are failing, I was receiving this message back from Moneris after digging in a bit - "API token mismatch". My guess is that Moneris has changed some API contract or their documentation is out of date. If you have any ideas on how to rectify this I would welcome a PR.

**Comment by russdot** [comment]
Hey @craigpaul thanks so much for the quick reply. Glad(?) to hear that it's not just me... I will keep an open channel if I find out anything more regarding the issue.

As it's not entirely clear what is causing the problem, I'll leave it up to your discretion as to whether or not the issue merits staying open. Cheers.

**Comment by tappleby** [comment]
Based on my experience, the moneris live QA environments often will go down as well. You can check the status here https://developer.moneris.com/More/Testing/QA%20Server%20Status
